version: '3'

services:
  # Angular app service
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: waste-disposal-fe # Replace with the Docker image name you used earlier
    container_name: waste-disposal-fe # Replace with a suitable container name
    ports:
      - "80:80" # Map port 4200 of the host to port 4200 of the container
    networks:
      - waste-disposal-fe

networks:
  waste-disposal-fe:
    driver: bridge